### ISSUE TITLE
[Bug] Crate fails to compile on 1.65.0-beta

### ISSUE THREAD

**Issue by TimDiekmann** [hashintel/hash#1094]
### Describe the bug

When compiling on `1.65.0-beta`, the following error occurs:
```
error[E0658]: use of unstable library feature 'backtrace_frames'
   --> src/fmt/hook.rs:823:23
    |
823 |             backtrace.frames().len(),
    |                       ^^^^^^
    |
    = note: see issue #79676 <https://github.com/rust-lang/rust/issues/79676> for more information
```

### Rust compiler

1.65.0-beta

### Host

aarch64-apple-darwin

### Target

aarch64-apple-darwin

### Version

latest git revision (cf5d85e)

### Features

std
