### PR TITLE
Test 1.65-beta channel

### LINKED ISSUE #1094: [Bug] Crate fails to compile on 1.65.0-beta
### Describe the bug

When compiling on `1.65.0-beta`, the following error occurs:
```
error[E0658]: use of unstable library feature 'backtrace_frames'
   --> src/fmt/hook.rs:823:23
    |
823 |             backtrace.frames().len(),
    |                       ^^^^^^
    |
    = note: see issue #79676 <https://github.com/rust-lang/rust/issues/79676> for more information
```

### To reproduce

_No response_

### Expected behavior

_No response_

### Rust compiler

1.65.0-beta

### Host

aarch64-apple-darwin

### Target

aarch64-apple-darwin

### Version

latest git revision (cf5d85e)

### Features

std

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

With 1.65, backtrace support is added, so it's possible to use it without a nightly toolchain. In order to properly support it, we need to test that release in CI as well.

## 🔗 Related links

- Fixes #1094 

## 🔍 What does this change?

- Add beta channel to CI (current beta is `1.65.0-beta.2`)
- Fix usage of a nightly feature to read the number of frames in a backtrace, it's now omitted in non-nightly channels
- Adjust documentation to show the non-nightly output

## 🛡 What tests cover this?

- All tests, which are running at 1.63 will also be tested on 1.65 (which are all tests which are not using the Provider API)

### CODE REVIEW

**Review by indietyp — APPROVED** [review]

**Review by Alfred-Mountfield — APPROVED** [review]
Looks good to me too. Thanks for the review @indietyp!
